name: Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages